action: fire-dom-event
browser_mod:
  service: browser_mod.popup
  data:
    title: Pati
    card_mod:
      style:
        #popup header
        .:
    style: |
      --popup-max-width: 400px;
    content:
      type: vertical-stack
      cards:
        - type: entities
          card_mod:
            class: content
          entities:
            - entity: person.pati
              secondary_info: last-changed

        - type: history-graph
          card_mod:
            style: |
              ha-card > div {
                padding: 0 2em 1em 1.6em !important;
              }
          entities:
            - entity: person.pati

        - type: glance
          card_mod:
            style: |
              ha-card > div {
                padding: 1em 1.5em 0.2em 1em !important;
                box-sizing: content-box;
              }
          show_state: false
          entities:

            - entity: device_tracker.58_20_59_b9_83_0c
              name: Router
              icon: mdi:wifi
              card_mod:
                style: &state |
                  state-badge {
                    color: {{ '#3182b7' if is_state(config.entity, 'home') else '#3c3f3f' }};
                  }

