default_config:

logger:
  default: warning

homeassistant:
  packages: !include_dir_named packages
  external_url: "https://my-home-arogut.duckdns.org"
  internal_url: "http://homeassistant.local:8123"
  allowlist_external_dirs:
    - /config

recorder:
  db_url: !secret recorder_db_url
  purge_keep_days: 30

frontend: !include themes.yaml
template: !include sidebar.yaml

# https://github.com/thomasloven/hass-lovelace_gen
lovelace_gen:

lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /hacsfiles/lovelace-layout-card/layout-card.js
      type: module
    - url: /hacsfiles/swipe-card/swipe-card.js
      type: module
    - url: /hacsfiles/kiosk-mode/kiosk-mode.js
      type: module
    - url: /hacsfiles/bar-card/bar-card.js
      type: module
    - url: /hacsfiles/lovelace-more-info-card/more-info-card.js
      type: module
    - url: /hacsfiles/apexcharts-card/apexcharts-card.js
      type: module
    - url: /hacsfiles/lovelace-xiaomi-vacuum-map-card/xiaomi-vacuum-map-card.js
      type: module
    - url: /hacsfiles/tabbed-card/tabbed-card.js
      type: module
    - url: /hacsfiles/lovelace-mushroom/mushroom.js
      type: module
    - url: /hacsfiles/lovelace-hui-element/hui-element.js
      type: module
    # local
    - url: /local/marked.min.js?v=4.2.1
      type: module
    - url: /local/vanilla-tilt.min.js?v=1.7.3
      type: module
    - url: /local/browser_mod_icon.js?v=0.5
      type: module
    - url: /local/fonts.css?v=2.1
      type: css

## Converts time and date into sentence for UI
sensor:
  - platform: time_date
    display_options:
      - time
      - date
      - date_time
      - date_time_utc
      - date_time_iso
      - time_date
      - time_utc
      - beat

  - platform: template
    sensors:

      ## Converts time and date into sentence for UI
      day:
        value_template: >
          {% set days = ["Poniedziałek", "Wtorek", "Środa", "Czwartek", "Piątek", "Sobota", "Niedziela"] %}
          {{ strptime(states('sensor.date'), '%Y-%m-%d').day }}
          {{ days[now().weekday()] }}

      month:
        value_template: >
          {% set months = ['Stycznia', 'Lutego', 'Marca', 'Kwietnia', 'Maja', 'Czerwca', 'Lipca', 'Sierpnia', 'Września', 'Października', 'Listopada', 'Grudnia'] %}
          {{ strptime(states('sensor.date'), '%Y-%m-%d').day }}
          {{ months[now().month-1] }}

      date_string:
        friendly_name: "Full Date"
        value_template: "{{ states('sensor.day') }}, {{ states('sensor.month') }} {{ now().year }}"

duckdns:
  domain: !secret duckdns_domain
  access_token: !secret duckdns_token

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - ::1
    - 172.16.0.0/12