button_card_templates:
  !include_dir_merge_named button_card_templates

kiosk_mode:
  hide_header: true

#resources:
#  # When you regenerate, the browser cache for this file will be invalidated
#  - url: !file /local/card-mod.js
#    type: module

views:
  - !include ui/main_swipe_view.yaml
