#homeassistant:
#  customize:
#    person.adrian:
#      entity_picture: /local/adrian.png
#    person.pati:
#      entity_picture: /local/pati.png

#person:
#  - name: Adrian
#    id: adrian
#    device_trackers:
#      - device_tracker.galaxy_a51_5g
#
#  - name: Pati
#    id: pati
#    device_trackers:
#      - device_tracker.oneplus7pro
#      - device_tracker.58_20_59_b9_83_0c

mqtt:
  sensor:
    - name: adrian_last_changed
      state_topic: homeassistant/persistence/adrian
      value_template: >
        {{ value | replace(' ', 'T') }}

    - name: pati_last_changed
      state_topic: homeassistant/persistence/pati
      value_template: >
        {{ value | replace(' ', 'T') }}

automation:
  - alias: person_home
    mode: parallel
    trigger:
      platform: state
      entity_id:
        - person.adrian
        - person.pati
      from:
        - home
        - not_home
      to:
        - home
        - not_home
    action:
      service: mqtt.publish
      data:
        topic_template: >
          homeassistant/persistence/{{ trigger.to_state.name | lower }}
        payload_template: >
          {{ now() }}
        retain: true