homeassistant:
  customize:
    vacuum.odkurzacz:
      icon: cil:roborock-vacuum
    sensor.odkurzacz_last_clean_end:
      friendly_name: Ostatnie sprzątanie
      icon: mdi:calendar-clock

template:
  - sensor:
      - unique_id: vacuum_filter
        state: >
          {% set entity_id = 'sensor.odkurzacz_filter_left' %}
          {{ (states(entity_id) | int(default=0) / 5400) | int(default=0) }}
        attributes:
          friendly_name: Filtr
          icon: cil:roborock-filter
          unit_of_measurement: '%'

      - unique_id: vacuum_mainbrush
        state: >
          {% set entity_id = 'sensor.odkurzacz_main_brush_left' %}
          {{ (states(entity_id) | int(default=0) / 10800) | int(default=0) }}
        attributes:
          friendly_name: Główna szczotka
          icon: cil:roborock-mainbrush
          unit_of_measurement: '%'

      - unique_id: vacuum_sensors
        state: >
          {% set entity_id = 'sensor.odkurzacz_sensor_dirty_left' %}
          {{ (states(entity_id) | int(default=0) / 1080) | int(default=0) }}
        attributes:
          friendly_name: Sensory
          icon: cil:roborock-sensor
          unit_of_measurement: '%'

      - unique_id: vacuum_sidebrush
        state: >
          {% set entity_id = 'sensor.odkurzacz_side_brush_left' %}
          {{ (states(entity_id) | int(default=0) / 7200) | int(default=0) }}
        attributes:
          friendly_name: Szczotka boczna
          icon: cil:roborock-sidebrush
          unit_of_measurement: '%'