settings:
  variables:
    translate_unknown: Nieznany
    translate_idle: Nieaktywny
    translate_home: W domu
    translate_not_home: Poza domem
    translate_available: dostępny
    translate_no_updates: brak aktualizacji
    translate_update_available: dostępna aktualizacja
    translate_updates_available: dostępne aktualizacje

    translate_on: Wł.
    translate_off: Wył.
    translate_cool: Chłodzenie
    translate_fan_only: Tylko wiatrak
    translate_playing: Gra
    translate_paused: Pauza
    translate_standby: Stand By
