sidebar-button:
  template:
    - settings
    - extra_styles
  variables:
    is_selected:
      [[[
        return false;
      ]]]
    notify: >
      [[[
        return false;
      ]]]
  size: 2vw
  custom_fields:
    notify: >
      [[[
        if (Number.isInteger(variables.notify)) {
            return variables.notify;
        } else if (variables.notify) {
            return `<span style="font-weight: 900;">!</span>`;
        }
      ]]]
  styles:
    grid:
      - grid-template-areas: |
          "n  i"
      - grid-template-columns: auto min-content
      - grid-template-rows: auto
      - gap: 1.3%
      - align-items: start
      - will-change: transform
    card:
      - transition: none
      - overflow: visible
      - --mdc-ripple-color: rgba(0, 0, 0, 0.8)
      - justify-self: left
      - border-style: none
      - color: >
          [[[
            return variables.is_selected
                ? '#4b5254'
                : '#97989c';
          ]]]
      - background-color: >
          [[[
            return variables.is_selected
                ? 'rgba(255, 255, 255, 0.85)'
                : 'rgba(115, 115, 115, 0)';
          ]]]
    icon:
      - color: >
          [[[
            return variables.is_selected
                ? '#4b5254'
                : '#97989c';
          ]]]
    custom_fields:
      notify:
        - display: >
            [[[
              if (Number.isInteger(variables.notify)) {
                  return variables.notify > 0
                      ? 'initial'
                      : 'none';
              }
              else if (variables.notify) {
                  return variables.notify
                      ? 'initial'
                      : 'none';
              }
            ]]]
        - position: absolute
        - font-weight: 700
        - color: '#d6d6d6'
        - background: '#8b3333'
        - border-radius: 50%
        - text-align: center
        - text-overflow: unset
        - z-index: 1
  tap_action:
    haptic: medium
  hold_action:
    action: block
  double_tap_action:
    action: block
